dataset_dir: "/home/zxf/IMETA_LAB/data_collection/data"
task_name: "piper_pick_and_place"
num_episodes: 2
save_rate: 50

robotif_arm_cfg:
  master_arm_right_topic: "/master_arm_right/joint_states"
  puppet_arm_right_topic: "/puppet_arm_right/joint_states"

camera_cfg:
  camera_names: ["cam_right_wrist"]
  img_right_topic: "/camera_right/color/image_raw"