dataset_dir: "/data/local/experiment_2025"
task_name: "teleop_pick_and_place"
save_rate: 200

robotif_arm_cfg:
  master_arm_right_topic: "/master_arm_right/joint_states"
  puppet_arm_right_topic: "/puppet_arm_right/joint_states"
  enable_left_arm: true
  master_arm_left_topic: "/master_arm_left/joint_states"
  puppet_arm_left_topic: "/puppet_arm_left/joint_states"

camera_cfg:
  img_right_topic: "/camera_right/color/image_raw"
  img_left_topic: "/camera_left/color/image_raw"
  img_front_topic: "/camera_front/color/image_raw"
  img_top_topic: "/camera_top/color/image_raw"
  enable_depth_image: true
  depth_right_topic: "/camera_right/depth/image_raw"
  depth_left_topic: "/camera_left/depth/image_raw"
  depth_front_topic: "/camera_front/depth/image_raw"
  depth_top_topic: "/camera_top/depth/image_raw"